name: SCA Scan

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sca-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Trivy Scan
      - name: Run Trivy SCA scan
        uses: aquasecurity/trivy-action@0.28.0
        env:
          # https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-11141034
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,aquasec/trivy-db,ghcr.io/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db,aquasec/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db
        with:
          scan-type: 'fs'  # SCA scanning
          format: 'json'
          output: trivy-report.json
          directory: . 
          
      # Checkmarx Scan
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://deu.iam.checkmarx.net/
          cx_tenant: accuknox-nfr
          cx_client_id: Ayush
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cxAction: ScaScan
          cxScaAccount: Ayush
          cxScaUsername: ayush@accuknox.com
          cxScaPassword: ${{ secrets.CX_PASSWORD }}
          cxExecutePackageDependency: true

      # Optional: Upload reports as artifact
      - name: Upload scan reports
        uses: actions/upload-artifact@v4
        with:
          name: sca-scan-reports
          path: |
            trivy-report.json
            checkmarx-report.json